import {
  LayoutDashboard,
  Users,
  Shield,
  Building2,
  Menu,
  Settings,
  Folder,
  FileText,
  Home,
  User,
  UserCog,
  UserPlus,
  UserCheck,
  UserX,
  Lock,
  Key,
  KeyRound,
  ShieldCheck,
  ShieldAlert,
  Database,
  Server,
  HardDrive,
  Cloud,
  Globe,
  Mail,
  MessageSquare,
  Bell,
  BellRing,
  Calendar,
  CalendarDays,
  Clock,
  Timer,
  Search,
  Filter,
  SlidersHorizontal,
  List,
  ListTree,
  Table,
  Grid3X3,
  LayoutGrid,
  Layers,
  Package,
  Box,
  Archive,
  Inbox,
  Send,
  Download,
  Upload,
  File,
  FileCode,
  FileJson,
  FileCog,
  FolderOpen,
  FolderTree,
  Image,
  Video,
  Music,
  Camera,
  Mic,
  Monitor,
  Smartphone,
  Tablet,
  Laptop,
  Cpu,
  MemoryStick,
  Wifi,
  Bluetooth,
  Printer,
  Scan,
  QrCode,
  Barcode,
  CreditCard,
  Wallet,
  Banknote,
  DollarSign,
  Euro,
  PoundSterling,
  TrendingUp,
  TrendingDown,
  BarChart,
  BarChart2,
  BarChart3,
  PieChart,
  LineChart,
  Activity,
  Heart,
  Star,
  Bookmark,
  Flag,
  Tag,
  Tags,
  Award,
  Trophy,
  Gift,
  ShoppingCart,
  ShoppingBag,
  Store,
  Truck,
  MapPin,
  Map,
  Navigation,
  Compass,
  Target,
  Crosshair,
  Eye,
  EyeOff,
  Glasses,
  Lightbulb,
  Zap,
  Battery,
  BatteryCharging,
  Power,
  Plug,
  Sun,
  Moon,
  CloudSun,
  CloudMoon,
  Thermometer,
  Droplet,
  Wind,
  Umbrella,
  Snowflake,
  Flame,
  Leaf,
  Trees,
  Mountain,
  Waves,
  Anchor,
  Plane,
  Car,
  Bus,
  Train,
  Ship,
  Rocket,
  Satellite,
  Radio,
  Tv,
  Gamepad2,
  Joystick,
  Dice5,
  Puzzle,
  Crown,
  Gem,
  Coins,
  PiggyBank,
  Vault,
  Scale,
  Gavel,
  Briefcase,
  Building,
  Factory,
  Warehouse,
  Hospital,
  GraduationCap,
  BookOpen,
  Library,
  Newspaper,
  Rss,
  Share2,
  Link,
  Unlink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  ClipboardList,
  ClipboardCheck,
  CheckSquare,
  XSquare,
  AlertCircle,
  AlertTriangle,
  Info,
  HelpCircle,
  CircleHelp,
  CircleAlert,
  CircleCheck,
  CircleX,
  Ban,
  Trash,
  Trash2,
  Eraser,
  Pencil,
  PenTool,
  Highlighter,
  Brush,
  Palette,
  Pipette,
  Ruler,
  Calculator,
  Binary,
  Code,
  Code2,
  Terminal,
  SquareTerminal,
  FileTerminal,
  Braces,
  Brackets,
  Hash,
  AtSign,
  Percent,
  Pi,
  Sigma,
  Infinity,
  Plus,
  Minus,
  X,
  Divide,
  Equal,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  ChevronDown,
  ChevronsRight,
  ChevronsLeft,
  ChevronsUp,
  ChevronsDown,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ArrowUpRight,
  ArrowDownLeft,
  CornerUpRight,
  CornerDownLeft,
  Undo,
  Redo,
  RefreshCw,
  RotateCw,
  RotateCcw,
  Repeat,
  Shuffle,
  Play,
  Pause,
  Square,
  Circle,
  Triangle,
  Pentagon,
  Hexagon,
  Octagon,
  Diamond,
  Sparkles,
  Wand2,
  Languages,
  Globe2,
  Earth,
  Network,
  Workflow,
  GitBranch,
  GitCommit,
  GitMerge,
  GitPullRequest,
  Github,
  Gitlab,
  Chrome,
  type LucideIcon,
} from 'lucide-react';

// 图标映射表
export const iconMap: Record<string, LucideIcon> = {
  // 基础导航
  LayoutDashboard,
  Home,
  Menu,
  List,
  ListTree,
  Grid3X3,
  LayoutGrid,
  Layers,

  // 用户相关
  Users,
  User,
  UserCog,
  UserPlus,
  UserCheck,
  UserX,

  // 权限安全
  Shield,
  ShieldCheck,
  ShieldAlert,
  Lock,
  Key,
  KeyRound,

  // 组织架构
  Building,
  Building2,
  Factory,
  Warehouse,
  Hospital,

  // 设置配置
  Settings,
  SlidersHorizontal,
  Filter,

  // 文件文件夹
  Folder,
  FolderOpen,
  FolderTree,
  File,
  FileText,
  FileCode,
  FileJson,
  FileCog,
  Archive,
  Package,
  Box,

  // 数据存储
  Database,
  Server,
  HardDrive,
  Cloud,

  // 通信
  Globe,
  Globe2,
  Earth,
  Mail,
  MessageSquare,
  Bell,
  BellRing,
  Send,
  Inbox,

  // 时间日程
  Calendar,
  CalendarDays,
  Clock,
  Timer,

  // 搜索
  Search,
  Target,
  Crosshair,

  // 数据表格
  Table,
  ClipboardList,

  // 财务金融
  CreditCard,
  Wallet,
  Banknote,
  DollarSign,
  Euro,
  PoundSterling,
  Coins,
  PiggyBank,
  Vault,

  // 图表分析
  TrendingUp,
  TrendingDown,
  BarChart,
  BarChart2,
  BarChart3,
  PieChart,
  LineChart,
  Activity,

  // 电商购物
  ShoppingCart,
  ShoppingBag,
  Store,
  Truck,

  // 位置地图
  MapPin,
  Map,
  Navigation,
  Compass,

  // 媒体
  Image,
  Video,
  Music,
  Camera,
  Mic,

  // 设备
  Monitor,
  Smartphone,
  Tablet,
  Laptop,
  Cpu,
  MemoryStick,
  Printer,

  // 网络连接
  Wifi,
  Bluetooth,
  Network,
  Link,
  Unlink,
  Share2,
  Rss,

  // 扫码
  Scan,
  QrCode,
  Barcode,

  // 标记收藏
  Heart,
  Star,
  Bookmark,
  Flag,
  Tag,
  Tags,
  Award,
  Trophy,
  Gift,
  Crown,
  Gem,

  // 状态提示
  Eye,
  EyeOff,
  Lightbulb,
  AlertCircle,
  AlertTriangle,
  Info,
  HelpCircle,
  CircleHelp,
  CircleAlert,
  CircleCheck,
  CircleX,
  Ban,
  CheckSquare,
  XSquare,

  // 编辑工具
  Pencil,
  PenTool,
  Highlighter,
  Brush,
  Palette,
  Eraser,
  Scissors,
  Copy,
  Clipboard,
  ClipboardCheck,
  Trash,
  Trash2,

  // 能源天气
  Zap,
  Battery,
  BatteryCharging,
  Power,
  Plug,
  Sun,
  Moon,
  CloudSun,
  CloudMoon,
  Thermometer,
  Droplet,
  Wind,
  Umbrella,
  Snowflake,
  Flame,

  // 自然
  Leaf,
  Trees,
  Mountain,
  Waves,

  // 交通
  Anchor,
  Plane,
  Car,
  Bus,
  Train,
  Ship,
  Rocket,
  Satellite,

  // 娱乐游戏
  Radio,
  Tv,
  Gamepad2,
  Joystick,
  Dice5,
  Puzzle,

  // 教育
  GraduationCap,
  BookOpen,
  Library,
  Newspaper,

  // 商业法律
  Briefcase,
  Scale,
  Gavel,

  // 代码开发
  Code,
  Code2,
  Terminal,
  SquareTerminal,
  FileTerminal,
  Braces,
  Brackets,
  Binary,

  // Git
  GitBranch,
  GitCommit,
  GitMerge,
  GitPullRequest,
  Github,
  Gitlab,

  // 符号
  Hash,
  AtSign,
  Percent,
  Calculator,
  Ruler,

  // 操作
  Download,
  Upload,
  RefreshCw,
  RotateCw,
  RotateCcw,
  Undo,
  Redo,
  Repeat,
  Shuffle,
  Play,
  Pause,

  // 国际化
  Languages,
  Workflow,

  // 箭头方向
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  ChevronDown,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,

  // 形状
  Square,
  Circle,
  Triangle,
  Diamond,
  Hexagon,

  // 特效
  Sparkles,
  Wand2,

  // 浏览器
  Chrome,
};

// 图标分类（用于图标选择器的分组显示）
export const iconCategories: Record<string, string[]> = {
  '基础导航': ['LayoutDashboard', 'Home', 'Menu', 'List', 'ListTree', 'Grid3X3', 'LayoutGrid', 'Layers'],
  '用户相关': ['Users', 'User', 'UserCog', 'UserPlus', 'UserCheck', 'UserX'],
  '权限安全': ['Shield', 'ShieldCheck', 'ShieldAlert', 'Lock', 'Key', 'KeyRound'],
  '组织架构': ['Building', 'Building2', 'Factory', 'Warehouse', 'Hospital'],
  '设置配置': ['Settings', 'SlidersHorizontal', 'Filter'],
  '文件文件夹': ['Folder', 'FolderOpen', 'FolderTree', 'File', 'FileText', 'FileCode', 'FileJson', 'FileCog', 'Archive', 'Package', 'Box'],
  '数据存储': ['Database', 'Server', 'HardDrive', 'Cloud'],
  '通信': ['Globe', 'Globe2', 'Earth', 'Mail', 'MessageSquare', 'Bell', 'BellRing', 'Send', 'Inbox'],
  '时间日程': ['Calendar', 'CalendarDays', 'Clock', 'Timer'],
  '搜索定位': ['Search', 'Target', 'Crosshair', 'MapPin', 'Map', 'Navigation', 'Compass'],
  '数据表格': ['Table', 'ClipboardList', 'BarChart', 'BarChart2', 'BarChart3', 'PieChart', 'LineChart', 'Activity', 'TrendingUp', 'TrendingDown'],
  '财务金融': ['CreditCard', 'Wallet', 'Banknote', 'DollarSign', 'Euro', 'PoundSterling', 'Coins', 'PiggyBank', 'Vault'],
  '电商购物': ['ShoppingCart', 'ShoppingBag', 'Store', 'Truck'],
  '媒体': ['Image', 'Video', 'Music', 'Camera', 'Mic'],
  '设备': ['Monitor', 'Smartphone', 'Tablet', 'Laptop', 'Cpu', 'MemoryStick', 'Printer'],
  '网络连接': ['Wifi', 'Bluetooth', 'Network', 'Link', 'Unlink', 'Share2', 'Rss', 'Scan', 'QrCode', 'Barcode'],
  '标记收藏': ['Heart', 'Star', 'Bookmark', 'Flag', 'Tag', 'Tags', 'Award', 'Trophy', 'Gift', 'Crown', 'Gem'],
  '状态提示': ['Eye', 'EyeOff', 'Lightbulb', 'AlertCircle', 'AlertTriangle', 'Info', 'HelpCircle', 'CircleCheck', 'CircleX', 'Ban', 'CheckSquare', 'XSquare'],
  '编辑工具': ['Pencil', 'PenTool', 'Highlighter', 'Brush', 'Palette', 'Eraser', 'Scissors', 'Copy', 'Clipboard', 'ClipboardCheck', 'Trash', 'Trash2'],
  '代码开发': ['Code', 'Code2', 'Terminal', 'SquareTerminal', 'FileTerminal', 'Braces', 'Brackets', 'Binary', 'GitBranch', 'GitCommit', 'GitMerge', 'GitPullRequest', 'Github', 'Gitlab'],
  '交通': ['Anchor', 'Plane', 'Car', 'Bus', 'Train', 'Ship', 'Rocket', 'Satellite'],
  '教育': ['GraduationCap', 'BookOpen', 'Library', 'Newspaper'],
  '商业法律': ['Briefcase', 'Scale', 'Gavel'],
  '天气自然': ['Sun', 'Moon', 'CloudSun', 'CloudMoon', 'Thermometer', 'Droplet', 'Wind', 'Umbrella', 'Snowflake', 'Flame', 'Leaf', 'Trees', 'Mountain', 'Waves'],
  '娱乐游戏': ['Radio', 'Tv', 'Gamepad2', 'Joystick', 'Dice5', 'Puzzle'],
  '能源': ['Zap', 'Battery', 'BatteryCharging', 'Power', 'Plug'],
  '国际化': ['Languages', 'Workflow'],
};

// 获取所有图标名称列表
export const iconNames = Object.keys(iconMap);

// 根据名称获取图标组件
export const getIcon = (name: string): LucideIcon | undefined => {
  return iconMap[name];
};
