// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: string;
};

export type LoginDto = {
    /**
     * 用户名
     */
    username: string;
    /**
     * 密码
     */
    password: string;
};

export type ChangePasswordDto = {
    /**
     * 旧密码
     */
    oldPassword: string;
    /**
     * 新密码
     */
    newPassword: string;
    /**
     * 确认密码
     */
    confirmPassword: string;
};

export type ResetPasswordDto = {
    /**
     * 邮箱
     */
    email: string;
};

export type CreateUserDto = {
    /**
     * 用户名
     */
    username: string;
    /**
     * 密码
     */
    password: string;
    /**
     * 邮箱
     */
    email: string;
    /**
     * 姓名
     */
    name: string;
    /**
     * 手机号
     */
    phone?: string;
    /**
     * 头像
     */
    avatar?: string;
    /**
     * 状态
     */
    status?: 'active' | 'inactive' | 'banned';
    /**
     * 角色ID列表
     */
    roleIds?: Array<string>;
    /**
     * 备注
     */
    remark?: string;
};

export type UpdateUserDto = {
    /**
     * 用户名
     */
    username?: string;
    /**
     * 密码
     */
    password?: string;
    /**
     * 邮箱
     */
    email?: string;
    /**
     * 姓名
     */
    name?: string;
    /**
     * 手机号
     */
    phone?: string;
    /**
     * 头像
     */
    avatar?: string;
    /**
     * 状态
     */
    status?: 'active' | 'inactive' | 'banned';
    /**
     * 角色ID列表
     */
    roleIds?: Array<string>;
    /**
     * 备注
     */
    remark?: string;
};

export type BatchDeleteDto = {
    /**
     * ID列表
     */
    ids: Array<string>;
};

export type UpdateStatusDto = {
    /**
     * 状态
     */
    status: 'active' | 'inactive' | 'banned';
};

export type AssignRolesDto = {
    /**
     * 角色ID列表
     */
    roleIds: Array<string>;
};

export type CreateRoleDto = {
    /**
     * 角色名称
     */
    name: string;
    /**
     * 角色编码
     */
    code: string;
    /**
     * 角色描述
     */
    description?: string;
    /**
     * 菜单ID列表
     */
    menuIds?: Array<string>;
    /**
     * 状态
     */
    status?: 'active' | 'inactive';
    /**
     * 排序
     */
    sortOrder?: number;
    /**
     * 备注
     */
    remark?: string;
};

export type UpdateRoleDto = {
    /**
     * 角色名称
     */
    name?: string;
    /**
     * 角色编码
     */
    code?: string;
    /**
     * 角色描述
     */
    description?: string;
    /**
     * 菜单ID列表
     */
    menuIds?: Array<string>;
    /**
     * 状态
     */
    status?: 'active' | 'inactive';
    /**
     * 排序
     */
    sortOrder?: number;
    /**
     * 备注
     */
    remark?: string;
};

export type AssignMenusDto = {
    /**
     * 菜单ID列表
     */
    menuIds: Array<string>;
};

export type CopyRoleDto = {
    /**
     * 新角色名称
     */
    name?: string;
};

export type CreateMenuDto = {
    /**
     * 菜单名称
     */
    name: string;
    /**
     * 国际化Key
     */
    i18nKey?: string;
    /**
     * 菜单类型
     */
    type: 'directory' | 'page' | 'button' | 'iframe';
    /**
     * 父菜单ID
     */
    parentId?: string;
    /**
     * 图标
     */
    icon?: string;
    /**
     * 路由路径
     */
    path?: string;
    /**
     * 组件路径
     */
    component?: string;
    /**
     * 外部链接
     */
    externalUrl?: string;
    /**
     * 是否在新标签页打开
     */
    openInNewTab?: boolean;
    /**
     * 排序
     */
    sortOrder?: number;
    /**
     * 状态
     */
    status?: 'active' | 'inactive';
    /**
     * 是否隐藏
     */
    hideInMenu?: boolean;
    /**
     * 是否缓存
     */
    keepAlive?: boolean;
    /**
     * 描述
     */
    description?: string;
    /**
     * 备注
     */
    remark?: string;
};

export type UpdateMenuDto = {
    /**
     * 菜单名称
     */
    name?: string;
    /**
     * 国际化Key
     */
    i18nKey?: string;
    /**
     * 菜单类型
     */
    type?: 'directory' | 'page' | 'button' | 'iframe';
    /**
     * 父菜单ID
     */
    parentId?: string;
    /**
     * 图标
     */
    icon?: string;
    /**
     * 路由路径
     */
    path?: string;
    /**
     * 组件路径
     */
    component?: string;
    /**
     * 外部链接
     */
    externalUrl?: string;
    /**
     * 是否在新标签页打开
     */
    openInNewTab?: boolean;
    /**
     * 排序
     */
    sortOrder?: number;
    /**
     * 状态
     */
    status?: 'active' | 'inactive';
    /**
     * 是否隐藏
     */
    hideInMenu?: boolean;
    /**
     * 是否缓存
     */
    keepAlive?: boolean;
    /**
     * 描述
     */
    description?: string;
    /**
     * 备注
     */
    remark?: string;
};

export type UpdateSortDto = {
    /**
     * 菜单排序数据
     */
    menus: Array<string>;
};

export type CopyMenuDto = {
    /**
     * 父菜单ID
     */
    parentId?: string;
};

export type CreateI18nModuleDto = {
    /**
     * 模块代码
     */
    code: string;
    /**
     * 模块名称
     */
    name: string;
    /**
     * 模块描述
     */
    description?: string;
    /**
     * 备注
     */
    remark?: string;
};

export type UpdateI18nModuleDto = {
    /**
     * 模块名称
     */
    name?: string;
    /**
     * 模块描述
     */
    description?: string;
    /**
     * 备注
     */
    remark?: string;
};

export type CreateI18nDto = {
    /**
     * 模块ID
     */
    moduleId: string;
    /**
     * 键名
     */
    key: string;
    /**
     * 中文
     */
    zhCn: string;
    /**
     * 英文
     */
    enUs: string;
    /**
     * 阿拉伯文
     */
    arSa: string;
    /**
     * 备注
     */
    remark?: string;
};

export type UpdateI18nDto = {
    /**
     * 键名
     */
    key?: string;
    /**
     * 中文
     */
    zhCn?: string;
    /**
     * 英文
     */
    enUs?: string;
    /**
     * 阿拉伯文
     */
    arSa?: string;
    /**
     * 备注
     */
    remark?: string;
};

export type TranslateDto = {
    /**
     * 要翻译的文本
     */
    text: string;
    /**
     * 源语言代码
     */
    from: string;
    /**
     * 目标语言代码
     */
    to: string;
};

export type AuthControllerLoginData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/nova-admin-api/auth/login';
};

export type AuthControllerLoginResponses = {
    201: unknown;
};

export type AuthControllerLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/nova-admin-api/auth/logout';
};

export type AuthControllerLogoutResponses = {
    201: unknown;
};

export type AuthControllerRefreshTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/nova-admin-api/auth/refresh-token';
};

export type AuthControllerRefreshTokenResponses = {
    201: unknown;
};

export type AuthControllerGetUserInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/nova-admin-api/auth/user-info';
};

export type AuthControllerGetUserInfoResponses = {
    200: unknown;
};

export type AuthControllerChangePasswordData = {
    body: ChangePasswordDto;
    path?: never;
    query?: never;
    url: '/nova-admin-api/auth/change-password';
};

export type AuthControllerChangePasswordResponses = {
    201: unknown;
};

export type AuthControllerResetPasswordData = {
    body: ResetPasswordDto;
    path?: never;
    query?: never;
    url: '/nova-admin-api/auth/reset-password';
};

export type AuthControllerResetPasswordResponses = {
    201: unknown;
};

export type AuthControllerVerifyTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/nova-admin-api/auth/verify-token';
};

export type AuthControllerVerifyTokenResponses = {
    200: unknown;
};

export type UsersControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 页码
         */
        page?: number;
        /**
         * 每页数量
         */
        pageSize?: number;
        /**
         * 搜索关键词
         */
        keyword?: string;
        /**
         * 状态
         */
        status?: 'active' | 'inactive' | 'banned';
        /**
         * 角色
         */
        role?: string;
    };
    url: '/nova-admin-api/users';
};

export type UsersControllerFindAllResponses = {
    200: unknown;
};

export type UsersControllerCreateData = {
    body: CreateUserDto;
    path?: never;
    query?: never;
    url: '/nova-admin-api/users';
};

export type UsersControllerCreateResponses = {
    201: unknown;
};

export type UsersControllerDeleteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/nova-admin-api/users/{id}';
};

export type UsersControllerDeleteResponses = {
    200: unknown;
};

export type UsersControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/nova-admin-api/users/{id}';
};

export type UsersControllerFindOneResponses = {
    200: unknown;
};

export type UsersControllerUpdateData = {
    body: UpdateUserDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/nova-admin-api/users/{id}';
};

export type UsersControllerUpdateResponses = {
    200: unknown;
};

export type UsersControllerBatchDeleteData = {
    body: BatchDeleteDto;
    path?: never;
    query?: never;
    url: '/nova-admin-api/users/batch';
};

export type UsersControllerBatchDeleteResponses = {
    201: unknown;
};

export type UsersControllerResetPasswordData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/nova-admin-api/users/{id}/reset-password';
};

export type UsersControllerResetPasswordResponses = {
    201: unknown;
};

export type UsersControllerUpdateStatusData = {
    body: UpdateStatusDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/nova-admin-api/users/{id}/status';
};

export type UsersControllerUpdateStatusResponses = {
    200: unknown;
};

export type UsersControllerAssignRolesData = {
    body: AssignRolesDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/nova-admin-api/users/{id}/roles';
};

export type UsersControllerAssignRolesResponses = {
    201: unknown;
};

export type UsersControllerGetUserPermissionsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/nova-admin-api/users/{id}/permissions';
};

export type UsersControllerGetUserPermissionsResponses = {
    200: unknown;
};

export type RolesControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 页码
         */
        page?: number;
        /**
         * 每页数量
         */
        pageSize?: number;
        /**
         * 搜索关键词
         */
        keyword?: string;
    };
    url: '/nova-admin-api/roles';
};

export type RolesControllerFindAllResponses = {
    200: unknown;
};

export type RolesControllerCreateData = {
    body: CreateRoleDto;
    path?: never;
    query?: never;
    url: '/nova-admin-api/roles';
};

export type RolesControllerCreateResponses = {
    201: unknown;
};

export type RolesControllerFindAllWithoutPaginationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/nova-admin-api/roles/all';
};

export type RolesControllerFindAllWithoutPaginationResponses = {
    200: unknown;
};

export type RolesControllerGetMenuTreeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/nova-admin-api/roles/menus/tree';
};

export type RolesControllerGetMenuTreeResponses = {
    200: unknown;
};

export type RolesControllerDeleteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/nova-admin-api/roles/{id}';
};

export type RolesControllerDeleteResponses = {
    200: unknown;
};

export type RolesControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/nova-admin-api/roles/{id}';
};

export type RolesControllerFindOneResponses = {
    200: unknown;
};

export type RolesControllerUpdateData = {
    body: UpdateRoleDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/nova-admin-api/roles/{id}';
};

export type RolesControllerUpdateResponses = {
    200: unknown;
};

export type RolesControllerBatchDeleteData = {
    body: BatchDeleteDto;
    path?: never;
    query?: never;
    url: '/nova-admin-api/roles/batch';
};

export type RolesControllerBatchDeleteResponses = {
    201: unknown;
};

export type RolesControllerGetRoleMenusData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/nova-admin-api/roles/{id}/menus';
};

export type RolesControllerGetRoleMenusResponses = {
    200: unknown;
};

export type RolesControllerAssignMenusData = {
    body: AssignMenusDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/nova-admin-api/roles/{id}/menus';
};

export type RolesControllerAssignMenusResponses = {
    201: unknown;
};

export type RolesControllerCopyRoleData = {
    body: CopyRoleDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/nova-admin-api/roles/{id}/copy';
};

export type RolesControllerCopyRoleResponses = {
    201: unknown;
};

export type MenusControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/nova-admin-api/menus';
};

export type MenusControllerFindAllResponses = {
    200: unknown;
};

export type MenusControllerCreateData = {
    body: CreateMenuDto;
    path?: never;
    query?: never;
    url: '/nova-admin-api/menus';
};

export type MenusControllerCreateResponses = {
    201: unknown;
};

export type MenusControllerFindTreeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/nova-admin-api/menus/tree';
};

export type MenusControllerFindTreeResponses = {
    200: unknown;
};

export type MenusControllerGetIconsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/nova-admin-api/menus/icons';
};

export type MenusControllerGetIconsResponses = {
    200: unknown;
};

export type MenusControllerDeleteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/nova-admin-api/menus/{id}';
};

export type MenusControllerDeleteResponses = {
    200: unknown;
};

export type MenusControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/nova-admin-api/menus/{id}';
};

export type MenusControllerFindOneResponses = {
    200: unknown;
};

export type MenusControllerUpdateData = {
    body: UpdateMenuDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/nova-admin-api/menus/{id}';
};

export type MenusControllerUpdateResponses = {
    200: unknown;
};

export type MenusControllerBatchDeleteData = {
    body: BatchDeleteDto;
    path?: never;
    query?: never;
    url: '/nova-admin-api/menus/batch';
};

export type MenusControllerBatchDeleteResponses = {
    201: unknown;
};

export type MenusControllerUpdateSortData = {
    body: UpdateSortDto;
    path?: never;
    query?: never;
    url: '/nova-admin-api/menus/sort';
};

export type MenusControllerUpdateSortResponses = {
    200: unknown;
};

export type MenusControllerCopyMenuData = {
    body: CopyMenuDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/nova-admin-api/menus/{id}/copy';
};

export type MenusControllerCopyMenuResponses = {
    201: unknown;
};

export type I18nModulesControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 页码
         */
        page?: number;
        /**
         * 每页数量
         */
        pageSize?: number;
        /**
         * 搜索关键词
         */
        keyword?: string;
    };
    url: '/nova-admin-api/i18n-modules';
};

export type I18nModulesControllerFindAllResponses = {
    200: unknown;
};

export type I18nModulesControllerCreateData = {
    body: CreateI18nModuleDto;
    path?: never;
    query?: never;
    url: '/nova-admin-api/i18n-modules';
};

export type I18nModulesControllerCreateResponses = {
    201: unknown;
};

export type I18nModulesControllerDeleteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/nova-admin-api/i18n-modules/{id}';
};

export type I18nModulesControllerDeleteResponses = {
    200: unknown;
};

export type I18nModulesControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/nova-admin-api/i18n-modules/{id}';
};

export type I18nModulesControllerFindOneResponses = {
    200: unknown;
};

export type I18nModulesControllerUpdateData = {
    body: UpdateI18nModuleDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/nova-admin-api/i18n-modules/{id}';
};

export type I18nModulesControllerUpdateResponses = {
    200: unknown;
};

export type I18nModulesControllerBatchDeleteData = {
    body: BatchDeleteDto;
    path?: never;
    query?: never;
    url: '/nova-admin-api/i18n-modules/batch';
};

export type I18nModulesControllerBatchDeleteResponses = {
    201: unknown;
};

export type I18nControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 页码
         */
        page?: number;
        /**
         * 每页数量
         */
        pageSize?: number;
        /**
         * 搜索关键词
         */
        keyword?: string;
        /**
         * 模块ID
         */
        moduleId?: string;
    };
    url: '/nova-admin-api/i18n';
};

export type I18nControllerFindAllResponses = {
    200: unknown;
};

export type I18nControllerCreateData = {
    body: CreateI18nDto;
    path?: never;
    query?: never;
    url: '/nova-admin-api/i18n';
};

export type I18nControllerCreateResponses = {
    201: unknown;
};

export type I18nControllerDeleteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/nova-admin-api/i18n/{id}';
};

export type I18nControllerDeleteResponses = {
    200: unknown;
};

export type I18nControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/nova-admin-api/i18n/{id}';
};

export type I18nControllerFindOneResponses = {
    200: unknown;
};

export type I18nControllerUpdateData = {
    body: UpdateI18nDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/nova-admin-api/i18n/{id}';
};

export type I18nControllerUpdateResponses = {
    200: unknown;
};

export type I18nControllerBatchDeleteData = {
    body: BatchDeleteDto;
    path?: never;
    query?: never;
    url: '/nova-admin-api/i18n/batch';
};

export type I18nControllerBatchDeleteResponses = {
    201: unknown;
};

export type I18nControllerGetAllTranslationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/nova-admin-api/i18n/translations/all';
};

export type I18nControllerGetAllTranslationsResponses = {
    200: unknown;
};

export type I18nControllerTranslateData = {
    body: TranslateDto;
    path?: never;
    query?: never;
    url: '/nova-admin-api/i18n/translate';
};

export type I18nControllerTranslateResponses = {
    201: unknown;
};
