// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: string;
};

export type LoginDto = {
    /**
     * 用户名
     */
    username: string;
    /**
     * 密码
     */
    password: string;
};

export type ChangePasswordDto = {
    /**
     * 旧密码
     */
    oldPassword: string;
    /**
     * 新密码
     */
    newPassword: string;
    /**
     * 确认密码
     */
    confirmPassword: string;
};

export type ResetPasswordDto = {
    /**
     * 邮箱
     */
    email: string;
};

export type CreateUserDto = {
    /**
     * 用户名
     */
    username: string;
    /**
     * 密码
     */
    password: string;
    /**
     * 邮箱
     */
    email: string;
    /**
     * 姓名
     */
    name: string;
    /**
     * 手机号
     */
    phone?: string;
    /**
     * 头像
     */
    avatar?: string;
    /**
     * 状态
     */
    status?: 'active' | 'inactive' | 'banned';
    /**
     * 角色ID列表
     */
    roleIds?: Array<string>;
    /**
     * 备注
     */
    remark?: string;
};

export type UpdateUserDto = {
    /**
     * 用户名
     */
    username?: string;
    /**
     * 密码
     */
    password?: string;
    /**
     * 邮箱
     */
    email?: string;
    /**
     * 姓名
     */
    name?: string;
    /**
     * 手机号
     */
    phone?: string;
    /**
     * 头像
     */
    avatar?: string;
    /**
     * 状态
     */
    status?: 'active' | 'inactive' | 'banned';
    /**
     * 角色ID列表
     */
    roleIds?: Array<string>;
    /**
     * 备注
     */
    remark?: string;
};

export type BatchDeleteDto = {
    /**
     * 翻译ID列表
     */
    ids: Array<string>;
};

export type UpdateStatusDto = {
    /**
     * 状态
     */
    status: 'active' | 'inactive' | 'banned';
};

export type AssignRolesDto = {
    /**
     * 角色ID列表
     */
    roleIds: Array<string>;
};

export type CreateRoleDto = {
    /**
     * 角色名称
     */
    name: string;
    /**
     * 角色编码
     */
    code: string;
    /**
     * 角色描述
     */
    description?: string;
    /**
     * 权限列表
     */
    permissions?: Array<string>;
    /**
     * 状态
     */
    status?: 'active' | 'inactive';
    /**
     * 排序
     */
    sortOrder?: number;
    /**
     * 备注
     */
    remark?: string;
};

export type UpdateRoleDto = {
    /**
     * 角色名称
     */
    name?: string;
    /**
     * 角色编码
     */
    code?: string;
    /**
     * 角色描述
     */
    description?: string;
    /**
     * 权限列表
     */
    permissions?: Array<string>;
    /**
     * 状态
     */
    status?: 'active' | 'inactive';
    /**
     * 排序
     */
    sortOrder?: number;
    /**
     * 备注
     */
    remark?: string;
};

export type AssignPermissionsDto = {
    /**
     * 权限列表
     */
    permissionIds: Array<string>;
};

export type CopyRoleDto = {
    /**
     * 新角色名称
     */
    name?: string;
};

export type CreateMenuDto = {
    /**
     * 菜单名称
     */
    name: string;
    /**
     * 国际化Key
     */
    i18nKey?: string;
    /**
     * 菜单类型
     */
    type: 'directory' | 'page' | 'button' | 'iframe';
    /**
     * 父菜单ID
     */
    parentId?: string;
    /**
     * 图标
     */
    icon?: string;
    /**
     * 路由路径
     */
    path?: string;
    /**
     * 组件路径
     */
    component?: string;
    /**
     * 外部链接
     */
    externalUrl?: string;
    /**
     * 是否在新标签页打开
     */
    openInNewTab?: boolean;
    /**
     * 权限标识
     */
    permission?: string;
    /**
     * 排序
     */
    sortOrder?: number;
    /**
     * 状态
     */
    status?: 'active' | 'inactive';
    /**
     * 是否隐藏
     */
    hideInMenu?: boolean;
    /**
     * 是否缓存
     */
    keepAlive?: boolean;
    /**
     * 描述
     */
    description?: string;
    /**
     * 备注
     */
    remark?: string;
};

export type UpdateMenuDto = {
    /**
     * 菜单名称
     */
    name?: string;
    /**
     * 国际化Key
     */
    i18nKey?: string;
    /**
     * 菜单类型
     */
    type?: 'directory' | 'page' | 'button' | 'iframe';
    /**
     * 父菜单ID
     */
    parentId?: string;
    /**
     * 图标
     */
    icon?: string;
    /**
     * 路由路径
     */
    path?: string;
    /**
     * 组件路径
     */
    component?: string;
    /**
     * 外部链接
     */
    externalUrl?: string;
    /**
     * 是否在新标签页打开
     */
    openInNewTab?: boolean;
    /**
     * 权限标识
     */
    permission?: string;
    /**
     * 排序
     */
    sortOrder?: number;
    /**
     * 状态
     */
    status?: 'active' | 'inactive';
    /**
     * 是否隐藏
     */
    hideInMenu?: boolean;
    /**
     * 是否缓存
     */
    keepAlive?: boolean;
    /**
     * 描述
     */
    description?: string;
    /**
     * 备注
     */
    remark?: string;
};

export type UpdateSortDto = {
    /**
     * 菜单排序数据
     */
    menus: Array<string>;
};

export type CopyMenuDto = {
    /**
     * 父菜单ID
     */
    parentId?: string;
};

export type BatchImportDto = {
    /**
     * 是否覆盖已存在的翻译
     */
    overwrite?: boolean;
    /**
     * 按语言分组的JSON格式翻译数据
     */
    data: {
        [key: string]: unknown;
    };
};

export type CreateI18nTranslationDto = {
    /**
     * 模块名称
     */
    module: string;
    /**
     * 翻译键名
     */
    key: string;
    /**
     * 中文翻译
     */
    zhCN: string;
    /**
     * 英文翻译
     */
    enUS: string;
    /**
     * 阿拉伯语翻译
     */
    arSA: string;
    /**
     * 备注说明
     */
    remark?: string;
};

export type UpdateI18nTranslationDto = {
    /**
     * 模块名称
     */
    module?: string;
    /**
     * 翻译键名
     */
    key?: string;
    /**
     * 中文翻译
     */
    zhCN?: string;
    /**
     * 英文翻译
     */
    enUS?: string;
    /**
     * 阿拉伯语翻译
     */
    arSA?: string;
    /**
     * 备注说明
     */
    remark?: string;
};

export type AuthControllerLoginData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type AuthControllerLoginResponses = {
    201: unknown;
};

export type AuthControllerLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type AuthControllerLogoutResponses = {
    201: unknown;
};

export type AuthControllerRefreshTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/refresh-token';
};

export type AuthControllerRefreshTokenResponses = {
    201: unknown;
};

export type AuthControllerGetUserInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/user-info';
};

export type AuthControllerGetUserInfoResponses = {
    200: unknown;
};

export type AuthControllerChangePasswordData = {
    body: ChangePasswordDto;
    path?: never;
    query?: never;
    url: '/api/auth/change-password';
};

export type AuthControllerChangePasswordResponses = {
    201: unknown;
};

export type AuthControllerResetPasswordData = {
    body: ResetPasswordDto;
    path?: never;
    query?: never;
    url: '/api/auth/reset-password';
};

export type AuthControllerResetPasswordResponses = {
    201: unknown;
};

export type AuthControllerVerifyTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/verify-token';
};

export type AuthControllerVerifyTokenResponses = {
    200: unknown;
};

export type UsersControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 页码
         */
        page?: number;
        /**
         * 每页数量
         */
        pageSize?: number;
        /**
         * 搜索关键词
         */
        keyword?: string;
        /**
         * 状态
         */
        status?: 'active' | 'inactive' | 'banned';
        /**
         * 角色
         */
        role?: string;
    };
    url: '/api/users';
};

export type UsersControllerFindAllResponses = {
    200: unknown;
};

export type UsersControllerCreateData = {
    body: CreateUserDto;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type UsersControllerCreateResponses = {
    201: unknown;
};

export type UsersControllerDeleteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type UsersControllerDeleteResponses = {
    200: unknown;
};

export type UsersControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type UsersControllerFindOneResponses = {
    200: unknown;
};

export type UsersControllerUpdateData = {
    body: UpdateUserDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type UsersControllerUpdateResponses = {
    200: unknown;
};

export type UsersControllerBatchDeleteData = {
    body: BatchDeleteDto;
    path?: never;
    query?: never;
    url: '/api/users/batch';
};

export type UsersControllerBatchDeleteResponses = {
    201: unknown;
};

export type UsersControllerResetPasswordData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/users/{id}/reset-password';
};

export type UsersControllerResetPasswordResponses = {
    201: unknown;
};

export type UsersControllerUpdateStatusData = {
    body: UpdateStatusDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/users/{id}/status';
};

export type UsersControllerUpdateStatusResponses = {
    200: unknown;
};

export type UsersControllerAssignRolesData = {
    body: AssignRolesDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/users/{id}/roles';
};

export type UsersControllerAssignRolesResponses = {
    201: unknown;
};

export type UsersControllerGetUserPermissionsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/users/{id}/permissions';
};

export type UsersControllerGetUserPermissionsResponses = {
    200: unknown;
};

export type RolesControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 页码
         */
        page?: number;
        /**
         * 每页数量
         */
        pageSize?: number;
        /**
         * 搜索关键词
         */
        keyword?: string;
    };
    url: '/api/roles';
};

export type RolesControllerFindAllResponses = {
    200: unknown;
};

export type RolesControllerCreateData = {
    body: CreateRoleDto;
    path?: never;
    query?: never;
    url: '/api/roles';
};

export type RolesControllerCreateResponses = {
    201: unknown;
};

export type RolesControllerFindAllWithoutPaginationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/roles/all';
};

export type RolesControllerFindAllWithoutPaginationResponses = {
    200: unknown;
};

export type RolesControllerGetPermissionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/roles/permissions';
};

export type RolesControllerGetPermissionsResponses = {
    200: unknown;
};

export type RolesControllerGetPermissionTreeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/roles/permissions/tree';
};

export type RolesControllerGetPermissionTreeResponses = {
    200: unknown;
};

export type RolesControllerDeleteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/roles/{id}';
};

export type RolesControllerDeleteResponses = {
    200: unknown;
};

export type RolesControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/roles/{id}';
};

export type RolesControllerFindOneResponses = {
    200: unknown;
};

export type RolesControllerUpdateData = {
    body: UpdateRoleDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/roles/{id}';
};

export type RolesControllerUpdateResponses = {
    200: unknown;
};

export type RolesControllerBatchDeleteData = {
    body: BatchDeleteDto;
    path?: never;
    query?: never;
    url: '/api/roles/batch';
};

export type RolesControllerBatchDeleteResponses = {
    201: unknown;
};

export type RolesControllerGetRolePermissionsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/roles/{id}/permissions';
};

export type RolesControllerGetRolePermissionsResponses = {
    200: unknown;
};

export type RolesControllerAssignPermissionsData = {
    body: AssignPermissionsDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/roles/{id}/permissions';
};

export type RolesControllerAssignPermissionsResponses = {
    201: unknown;
};

export type RolesControllerCopyRoleData = {
    body: CopyRoleDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/roles/{id}/copy';
};

export type RolesControllerCopyRoleResponses = {
    201: unknown;
};

export type MenusControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/menus';
};

export type MenusControllerFindAllResponses = {
    200: unknown;
};

export type MenusControllerCreateData = {
    body: CreateMenuDto;
    path?: never;
    query?: never;
    url: '/api/menus';
};

export type MenusControllerCreateResponses = {
    201: unknown;
};

export type MenusControllerFindTreeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/menus/tree';
};

export type MenusControllerFindTreeResponses = {
    200: unknown;
};

export type MenusControllerGetIconsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/menus/icons';
};

export type MenusControllerGetIconsResponses = {
    200: unknown;
};

export type MenusControllerDeleteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/menus/{id}';
};

export type MenusControllerDeleteResponses = {
    200: unknown;
};

export type MenusControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/menus/{id}';
};

export type MenusControllerFindOneResponses = {
    200: unknown;
};

export type MenusControllerUpdateData = {
    body: UpdateMenuDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/menus/{id}';
};

export type MenusControllerUpdateResponses = {
    200: unknown;
};

export type MenusControllerBatchDeleteData = {
    body: BatchDeleteDto;
    path?: never;
    query?: never;
    url: '/api/menus/batch';
};

export type MenusControllerBatchDeleteResponses = {
    201: unknown;
};

export type MenusControllerUpdateSortData = {
    body: UpdateSortDto;
    path?: never;
    query?: never;
    url: '/api/menus/sort';
};

export type MenusControllerUpdateSortResponses = {
    200: unknown;
};

export type MenusControllerCopyMenuData = {
    body: CopyMenuDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/menus/{id}/copy';
};

export type MenusControllerCopyMenuResponses = {
    201: unknown;
};

export type I18nControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 页码
         */
        page?: number;
        /**
         * 每页数量
         */
        pageSize?: number;
        /**
         * 按模块筛选
         */
        module?: string;
        /**
         * 搜索关键词（搜索key或翻译值）
         */
        keyword?: string;
    };
    url: '/api/i18n';
};

export type I18nControllerFindAllResponses = {
    200: unknown;
};

export type I18nControllerCreateData = {
    body: CreateI18nTranslationDto;
    path?: never;
    query?: never;
    url: '/api/i18n';
};

export type I18nControllerCreateResponses = {
    201: unknown;
};

export type I18nControllerGetNestedTranslationsData = {
    body?: never;
    path: {
        language: string;
    };
    query?: never;
    url: '/api/i18n/nested/{language}';
};

export type I18nControllerGetNestedTranslationsResponses = {
    200: unknown;
};

export type I18nControllerGetAllTranslationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/i18n/all';
};

export type I18nControllerGetAllTranslationsResponses = {
    200: unknown;
};

export type I18nControllerGetModulesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/i18n/modules';
};

export type I18nControllerGetModulesResponses = {
    200: unknown;
};

export type I18nControllerBatchDeleteData = {
    body: BatchDeleteDto;
    path?: never;
    query?: never;
    url: '/api/i18n/batch-delete';
};

export type I18nControllerBatchDeleteResponses = {
    201: unknown;
};

export type I18nControllerImportFromJsonData = {
    body: BatchImportDto;
    path?: never;
    query?: never;
    url: '/api/i18n/import/json';
};

export type I18nControllerImportFromJsonResponses = {
    201: unknown;
};

export type I18nControllerExportToJsonData = {
    body?: never;
    path: {
        language: string;
    };
    query?: never;
    url: '/api/i18n/export/json/{language}';
};

export type I18nControllerExportToJsonResponses = {
    200: unknown;
};

export type I18nControllerDeleteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/i18n/{id}';
};

export type I18nControllerDeleteResponses = {
    200: unknown;
};

export type I18nControllerFindByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/i18n/{id}';
};

export type I18nControllerFindByIdResponses = {
    200: unknown;
};

export type I18nControllerUpdateData = {
    body: UpdateI18nTranslationDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/i18n/{id}';
};

export type I18nControllerUpdateResponses = {
    200: unknown;
};
